const IMAGE_MAP={pommes:'images/pommes.svg',tarte:'images/tarte.svg',chocolat:'images/choco.svg',default:'images/legumes.svg'};
function getImage(recipe){const s=(recipe.title+' '+recipe.ingredients).toLowerCase();if(/pomme|avoine|muesli/.test(s))return IMAGE_MAP.pommes;if(/tarte|pât|pate|pâte/.test(s))return IMAGE_MAP.tarte;if(/chocolat|cacao/.test(s))return IMAGE_MAP.chocolat;return IMAGE_MAP.default}
const starterRecipes=[{id:1,title:'Muesli aux pommes et cannelle',ingredients:'pommes, flocons d’avoine, lait, cannelle',instructions:'Couper les pommes en morceaux, mélanger avec les flocons d’avoine, saupoudrer de cannelle et ajouter le lait.',scheduledDate:null},{id:2,title:'Tarte aux pommes rapide',ingredients:'pâte feuilletée, pommes, sucre, beurre',instructions:'Disposer la pâte dans un plat, ajouter les lamelles de pommes, saupoudrer de sucre et de noisettes de beurre. Cuire 30 min.',scheduledDate:null}];
let recipes=JSON.parse(localStorage.getItem('my_recipes')||'null')||starterRecipes;let selectedRecipeForSchedule=null;let selectedRecipeForDetail=null;
const navItems=document.querySelectorAll('.nav-item'),tabs=document.querySelectorAll('.tab-content');
navItems.forEach(item=>item.addEventListener('click',()=>{navItems.forEach(n=>n.classList.remove('active'));tabs.forEach(t=>t.classList.remove('active'));item.classList.add('active');const target=item.dataset.tab;document.getElementById('tab-'+target).classList.add('active');if(target==='calendar')renderCalendar();else renderRecipes(searchInput.value)}));
const searchInput=document.getElementById('search-input'),recipesResults=document.getElementById('recipes-results'),count=document.getElementById('recipe-count'),resultsTitle=document.getElementById('results-title');
searchInput.addEventListener('input',()=>renderRecipes(searchInput.value));
function renderRecipes(value=''){const q=value.toLowerCase().trim();const filtered=recipes.filter(r=>!q||(r.title+' '+r.ingredients).toLowerCase().includes(q));count.textContent=filtered.length;resultsTitle.textContent=q?`Résultats pour « ${value.trim()} »`:'Toutes mes recettes';recipesResults.innerHTML='';if(!filtered.length){recipesResults.innerHTML='<div class="empty-state"><span class="empty-icon">🧺</span>Aucune recette trouvée.<br>Essaie un autre ingrédient ou ajoute une nouvelle recette avec le bouton +.</div>';return}filtered.forEach(recipe=>{const card=document.createElement('article');card.className='recipe-card';const img=document.createElement('div');img.className='recipe-image';img.style.backgroundImage=`url("${getImage(recipe)}")`;const body=document.createElement('div');body.className='recipe-body';body.innerHTML=`<div class="recipe-title">${escapeHtml(recipe.title)}</div><div class="recipe-ingredients">${escapeHtml(recipe.ingredients)}</div><span class="recipe-tag">IG bas • fait maison</span>${recipe.scheduledDate?`<div class="scheduled-badge">📅 ${formatDate(recipe.scheduledDate)}</div>`:''}`;card.append(img,body);card.addEventListener('click',()=>openRecipeDetail(recipe));recipesResults.appendChild(card)})}
const addModal=document.getElementById('add-modal'),openAdd=document.getElementById('open-add-modal-btn');openAdd.addEventListener('click',()=>addModal.style.display='flex');document.getElementById('close-modal-btn').addEventListener('click',()=>addModal.style.display='none');
document.getElementById('save-new-recipe-btn').addEventListener('click',()=>{const title=document.getElementById('new-title').value.trim(),ingredients=document.getElementById('new-ingredients').value.trim(),instructions=document.getElementById('new-instructions').value.trim();if(!title||!ingredients||!instructions){alert('Merci de remplir tous les champs !');return}recipes.push({id:Date.now(),title,ingredients,instructions,scheduledDate:null});save();['new-title','new-ingredients','new-instructions'].forEach(id=>document.getElementById(id).value='');addModal.style.display='none';renderRecipes(searchInput.value)});
const scheduleModal=document.getElementById('schedule-modal');document.getElementById('close-schedule-btn').addEventListener('click',()=>scheduleModal.style.display='none');document.getElementById('confirm-schedule-btn').addEventListener('click',()=>{const date=document.getElementById('schedule-date-input').value;if(!date){alert('Choisis une date !');return}selectedRecipeForSchedule.scheduledDate=date;save();scheduleModal.style.display='none';renderRecipes(searchInput.value);renderCalendar();});
function openScheduleModal(recipe){selectedRecipeForSchedule=recipe;document.getElementById('schedule-recipe-title').textContent=recipe.title;document.getElementById('schedule-date-input').value=recipe.scheduledDate||'';scheduleModal.style.display='flex'}
function openRecipeDetail(recipe){selectedRecipeForDetail=recipe;document.getElementById('detail-recipe-image').style.backgroundImage=`url("${getImage(recipe)}")`;document.getElementById('detail-recipe-title').textContent=recipe.title;document.getElementById('detail-recipe-ingredients').textContent=recipe.ingredients;document.getElementById('detail-recipe-instructions').textContent=recipe.instructions;const badge=document.getElementById('detail-recipe-date');if(recipe.scheduledDate){badge.textContent='📅 Prévu le '+formatDate(recipe.scheduledDate);badge.style.display='inline-block'}else badge.style.display='none';document.getElementById('recipe-detail-modal').style.display='flex'}
const detailModal=document.getElementById('recipe-detail-modal');document.getElementById('close-recipe-detail-btn').addEventListener('click',()=>detailModal.style.display='none');document.getElementById('detail-plan-btn').addEventListener('click',()=>{detailModal.style.display='none';openScheduleModal(selectedRecipeForDetail)});
function renderCalendar(){const container=document.getElementById('calendar-days-container');container.innerHTML='';const scheduled=recipes.filter(r=>r.scheduledDate).sort((a,b)=>new Date(a.scheduledDate)-new Date(b.scheduledDate));if(!scheduled.length){container.innerHTML='<div class="empty-state"><span class="empty-icon">🌷</span>Ton calendrier est encore tout léger.<br>Ouvre une recette puis choisis une date pour la programmer.</div>';return}const groups={};scheduled.forEach(r=>(groups[r.scheduledDate]??=[]).push(r));Object.entries(groups).forEach(([date,recs])=>{const box=document.createElement('div');box.className='calendar-day-box';const title=document.createElement('div');title.className='calendar-day-title';title.textContent='📅 '+formatDate(date);box.appendChild(title);recs.forEach(r=>{const item=document.createElement('div');item.className='calendar-recipe-item';const mini=document.createElement('div');mini.className='calendar-mini-image';mini.style.backgroundImage=`url("${getImage(r)}")`;const name=document.createElement('div');name.className='calendar-recipe-name';name.innerHTML=`<strong>${escapeHtml(r.title)}</strong>`;const arrow=document.createElement('span');arrow.className='calendar-arrow';arrow.textContent='›';const del=document.createElement('button');del.className='delete-schedule-btn';del.textContent='×';del.setAttribute('aria-label','Retirer');del.addEventListener('click',e=>{e.stopPropagation();r.scheduledDate=null;save();renderCalendar()});item.append(mini,name,arrow,del);item.addEventListener('click',()=>openRecipeDetail(r));box.appendChild(item)});container.appendChild(box)})}
function save(){localStorage.setItem('my_recipes',JSON.stringify(recipes))}function formatDate(s){return new Date(s+'T00:00:00').toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}function escapeHtml(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
[addModal,scheduleModal,detailModal].forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.style.display='none'}));
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(()=>{}));
renderRecipes();
